server:
  port: 5000
  servlet:
    contextPath: /
    session:
      timeout: 1800
  jetty:
    max-http-form-post-size: 200000B

logging:
  level:
    com.jesse.training.spring: DEBUG
    org.eclipse.jetty: INFO
#    org.springframework:
#      debug

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect